[model_providers.hyperbolic]
base_url = "https://api.hyperbolic.xyz/v1"
name = "hyperbolic"
wire_api = "chat"
env_key = "HYPERBOLIC_API_KEY"

[profiles.hyp_flux_1_dev]
approval_policy = "never"
model = "FLUX.1-dev"
model_provider = "hyperbolic"
model_reasoning_effort = "high"

[profiles.hyp_nousresearch_hermes_]
approval_policy = "never"
model = "NousResearch/Hermes-3-Llama-3.1-70B"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 12288

[profiles.hyp_qwen_qwq_32b]
approval_policy = "never"
model = "Qwen/QwQ-32B"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.hyp_qwen_qwq_32b_preview]
approval_policy = "never"
model = "Qwen/QwQ-32B-Preview"
model_provider = "hyperbolic"
model_reasoning_effort = "high"

[profiles.hyp_qwen_qwen2_5_72b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-72B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.hyp_qwen_qwen2_5_coder_3]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-32B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.hyp_qwen_qwen2_5_vl_72b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-72B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.hyp_qwen_qwen2_5_vl_7b_i]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-7B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.hyp_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.hyp_qwen_qwen3_coder_480]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.hyp_sdxl1_0_base]
approval_policy = "never"
model = "SDXL1.0-base"
model_provider = "hyperbolic"
model_reasoning_effort = "high"

[profiles.hyp_tts]
approval_policy = "never"
model = "TTS"
model_provider = "hyperbolic"
model_reasoning_effort = "high"

[profiles.hyp_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai/DeepSeek-V3-0324"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 163840

[profiles.hyp_meta_llama_llama_3_2]
approval_policy = "never"
model = "meta-llama/Llama-3.2-3B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.hyp_meta_llama_llama_3_3]
approval_policy = "never"
model = "meta-llama/Llama-3.3-70B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.hyp_meta_llama_meta_llam]
approval_policy = "never"
model = "meta-llama/Meta-Llama-3.1-8B-Instruct"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.hyp_mistralai_pixtral_12]
approval_policy = "never"
model = "mistralai/Pixtral-12B-2409"
model_provider = "hyperbolic"
model_reasoning_effort = "high"
model_context_window = 32768
