[model_providers.huggingface]
base_url = "https://router.huggingface.co/v1"
name = "huggingface"
wire_api = "chat"
env_key = "HUGGINGFACEHUB_API_TOKEN"

[profiles.hug_coherelabs_aya_expan]
approval_policy = "never"
model = "CohereLabs/aya-expanse-8b"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_coherelabs_aya_visio]
approval_policy = "never"
model = "CohereLabs/aya-vision-8b"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_coherelabs_c4ai_comm]
approval_policy = "never"
model = "CohereLabs/c4ai-command-r7b-arabic-02-2025"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_coherelabs_command_a]
approval_policy = "never"
model = "CohereLabs/command-a-vision-07-2025"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_huggingfacetb_smollm]
approval_policy = "never"
model = "HuggingFaceTB/SmolLM3-3B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_minimaxai_minimax_m1]
approval_policy = "never"
model = "MiniMaxAI/MiniMax-M1-80k"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_nousresearch_hermes_]
approval_policy = "never"
model = "NousResearch/Hermes-4-70B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwq_32b]
approval_policy = "never"
model = "Qwen/QwQ-32B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwq_32b_preview]
approval_policy = "never"
model = "Qwen/QwQ-32B-Preview"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_vl_72b_in]
approval_policy = "never"
model = "Qwen/Qwen2-VL-72B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_32b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-32B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_72b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-72B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_7b_inst]
approval_policy = "never"
model = "Qwen/Qwen2.5-7B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_coder_3]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-3B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_coder_7]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-7B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_vl_32b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-32B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_vl_72b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-72B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen2_5_vl_7b_i]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-7B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_14b]
approval_policy = "never"
model = "Qwen/Qwen3-14B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen/Qwen3-235B-A22B-Thinking-2507"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_30b_a3b]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_30b_a3b_i]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_30b_a3b_t]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B-Thinking-2507"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_32b]
approval_policy = "never"
model = "Qwen/Qwen3-32B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_4b]
approval_policy = "never"
model = "Qwen/Qwen3-4B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_4b_instru]
approval_policy = "never"
model = "Qwen/Qwen3-4B-Instruct-2507"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_4b_thinki]
approval_policy = "never"
model = "Qwen/Qwen3-4B-Thinking-2507"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_8b]
approval_policy = "never"
model = "Qwen/Qwen3-8B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_coder_30b]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-30B-A3B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_qwen_qwen3_coder_480]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_sao10k_l3_70b_euryal]
approval_policy = "never"
model = "Sao10K/L3-70B-Euryale-v2.1"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_sao10k_l3_8b_lunaris]
approval_policy = "never"
model = "Sao10K/L3-8B-Lunaris-v1"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_sao10k_l3_8b_stheno_]
approval_policy = "never"
model = "Sao10K/L3-8B-Stheno-v3.2"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_sentientagi_dobby_un]
approval_policy = "never"
model = "SentientAGI/Dobby-Unhinged-Llama-3.3-70B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_aaditya_llama3_openb]
approval_policy = "never"
model = "aaditya/Llama3-OpenBioLLM-70B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_alpindale_wizardlm_2]
approval_policy = "never"
model = "alpindale/WizardLM-2-8x22B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_arcee_ai_afm_4_5b]
approval_policy = "never"
model = "arcee-ai/AFM-4.5B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baichuan_inc_baichua]
approval_policy = "never"
model = "baichuan-inc/Baichuan-M2-32B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baidu_ernie_4_5_0_3b]
approval_policy = "never"
model = "baidu/ERNIE-4.5-0.3B-PT"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baidu_ernie_4_5_21b_]
approval_policy = "never"
model = "baidu/ERNIE-4.5-21B-A3B-PT"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baidu_ernie_4_5_300b]
approval_policy = "never"
model = "baidu/ERNIE-4.5-300B-A47B-Base-PT"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baidu_ernie_4_5_vl_2]
approval_policy = "never"
model = "baidu/ERNIE-4.5-VL-28B-A3B-PT"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_baidu_ernie_4_5_vl_4]
approval_policy = "never"
model = "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai/DeepSeek-V3.1"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_dphn_dolphin_2_9_2_m]
approval_policy = "never"
model = "dphn/dolphin-2.9.2-mixtral-8x22b"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_google_gemma_2_2b_it]
approval_policy = "never"
model = "google/gemma-2-2b-it"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_google_gemma_2_9b_it]
approval_policy = "never"
model = "google/gemma-2-9b-it"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_google_gemma_3_27b_i]
approval_policy = "never"
model = "google/gemma-3-27b-it"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_marin_community_mari]
approval_policy = "never"
model = "marin-community/marin-8b-instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_3_1]
approval_policy = "never"
model = "meta-llama/Llama-3.1-8B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_3_2]
approval_policy = "never"
model = "meta-llama/Llama-3.2-3B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_3_3]
approval_policy = "never"
model = "meta-llama/Llama-3.3-70B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_4_m]
approval_policy = "never"
model = "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_4_s]
approval_policy = "never"
model = "meta-llama/Llama-4-Scout-17B-16E-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_llama_gua]
approval_policy = "never"
model = "meta-llama/Llama-Guard-4-12B"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_meta_llama_meta_llam]
approval_policy = "never"
model = "meta-llama/Meta-Llama-3-8B-Instruct"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_microsoft_phi_4]
approval_policy = "never"
model = "microsoft/phi-4"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_moonshotai_kimi_k2_i]
approval_policy = "never"
model = "moonshotai/Kimi-K2-Instruct-0905"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_nvidia_llama_3_1_nem]
approval_policy = "never"
model = "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_nvidia_llama_3_3_nem]
approval_policy = "never"
model = "nvidia/Llama-3_3-Nemotron-Super-49B-v1"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_openai_gpt_oss_120b]
approval_policy = "never"
model = "openai/gpt-oss-120b"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_openai_gpt_oss_20b]
approval_policy = "never"
model = "openai/gpt-oss-20b"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_tokyotech_llm_llama_]
approval_policy = "never"
model = "tokyotech-llm/Llama-3.3-Swallow-70B-Instruct-v0.4"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_32b_04]
approval_policy = "never"
model = "zai-org/GLM-4-32B-0414"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_1v_9b_]
approval_policy = "never"
model = "zai-org/GLM-4.1V-9B-Thinking"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_5]
approval_policy = "never"
model = "zai-org/GLM-4.5"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_5_air]
approval_policy = "never"
model = "zai-org/GLM-4.5-Air"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_5_air_]
approval_policy = "never"
model = "zai-org/GLM-4.5-Air-FP8"
model_provider = "huggingface"
model_reasoning_effort = "high"

[profiles.hug_zai_org_glm_4_5v]
approval_policy = "never"
model = "zai-org/GLM-4.5V"
model_provider = "huggingface"
model_reasoning_effort = "high"
