[model_providers.togetherai]
base_url = "https://api.together.xyz/v1"
name = "togetherai"
wire_api = "chat"
env_key = "TOGETHERAI_API_KEY"

[profiles.tog_alibaba_nlp_gte_mode]
approval_policy = "never"
model = "Alibaba-NLP/gte-modernbert-base"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_baai_bge_base_en_v1_]
approval_policy = "never"
model = "BAAI/bge-base-en-v1.5"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 512

[profiles.tog_baai_bge_large_en_v1]
approval_policy = "never"
model = "BAAI/bge-large-en-v1.5"
model_provider = "togetherai"
model_reasoning_effort = "high"

[profiles.tog_qwen_qwq_32b]
approval_policy = "never"
model = "Qwen/QwQ-32B"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_qwen_qwen2_5_72b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-72B-Instruct-Turbo"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_qwen_qwen2_5_7b_inst]
approval_policy = "never"
model = "Qwen/Qwen2.5-7B-Instruct-Turbo"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_qwen_qwen2_5_coder_3]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-32B-Instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 16384

[profiles.tog_qwen_qwen2_5_vl_72b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-72B-Instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen/Qwen3-235B-A22B-fp8-tput"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.tog_qwen_qwen3_coder_480]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.tog_salesforce_llama_ran]
approval_policy = "never"
model = "Salesforce/Llama-Rank-V1"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_virtue_ai_virtueguar]
approval_policy = "never"
model = "Virtue-AI/VirtueGuard-Text-Lite"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_arcee_ai_afm_4_5b]
approval_policy = "never"
model = "arcee-ai/AFM-4.5B"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 65536

[profiles.tog_arcee_ai_coder_large]
approval_policy = "never"
model = "arcee-ai/coder-large"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_arcee_ai_maestro_rea]
approval_policy = "never"
model = "arcee-ai/maestro-reasoning"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_arcee_ai_virtuoso_la]
approval_policy = "never"
model = "arcee-ai/virtuoso-large"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_arcee_ai_arcee_spotl]
approval_policy = "never"
model = "arcee_ai/arcee-spotlight"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_arize_ai_qwen_2_1_5b]
approval_policy = "never"
model = "arize-ai/qwen-2-1.5b-instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_black_forest_labs_fl]
approval_policy = "never"
model = "black-forest-labs/FLUX.1.1-pro"
model_provider = "togetherai"
model_reasoning_effort = "high"

[profiles.tog_cartesia_sonic]
approval_policy = "never"
model = "cartesia/sonic"
model_provider = "togetherai"
model_reasoning_effort = "high"

[profiles.tog_cartesia_sonic_2]
approval_policy = "never"
model = "cartesia/sonic-2"
model_provider = "togetherai"
model_reasoning_effort = "high"

[profiles.tog_deepcogito_cogito_v2]
approval_policy = "never"
model = "deepcogito/cogito-v2-preview-llama-70B"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai/DeepSeek-V3.1"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_google_gemma_3n_e4b_]
approval_policy = "never"
model = "google/gemma-3n-E4B-it"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_intfloat_multilingua]
approval_policy = "never"
model = "intfloat/multilingual-e5-large-instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 514

[profiles.tog_lgai_exaone_3_5_32b_]
approval_policy = "never"
model = "lgai/exaone-3-5-32b-instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_lgai_exaone_deep_32b]
approval_policy = "never"
model = "lgai/exaone-deep-32b"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_marin_community_mari]
approval_policy = "never"
model = "marin-community/marin-8b-instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 4096

[profiles.tog_meta_llama_llama_2_7]
approval_policy = "never"
model = "meta-llama/Llama-2-70b-hf"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 4096

[profiles.tog_meta_llama_llama_3_7]
approval_policy = "never"
model = "meta-llama/Llama-3-70b-hf"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_meta_llama_llama_3_1]
approval_policy = "never"
model = "meta-llama/Llama-3.1-405B-Instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 4096

[profiles.tog_meta_llama_llama_3_2]
approval_policy = "never"
model = "meta-llama/Llama-3.2-3B-Instruct-Turbo"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_meta_llama_llama_3_3]
approval_policy = "never"
model = "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_meta_llama_llama_4_m]
approval_policy = "never"
model = "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 1048576

[profiles.tog_meta_llama_llama_4_s]
approval_policy = "never"
model = "meta-llama/Llama-4-Scout-17B-16E-Instruct"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 1048576

[profiles.tog_meta_llama_llama_gua]
approval_policy = "never"
model = "meta-llama/Llama-Guard-4-12B"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 1048576

[profiles.tog_meta_llama_llamaguar]
approval_policy = "never"
model = "meta-llama/LlamaGuard-2-8b"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_meta_llama_meta_llam]
approval_policy = "never"
model = "meta-llama/Meta-Llama-Guard-3-8B"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_mistralai_mistral_7b]
approval_policy = "never"
model = "mistralai/Mistral-7B-Instruct-v0.3"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_mistralai_mistral_sm]
approval_policy = "never"
model = "mistralai/Mistral-Small-24B-Instruct-2501"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_mistralai_mixtral_8x]
approval_policy = "never"
model = "mistralai/Mixtral-8x7B-Instruct-v0.1"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_mixedbread_ai_mxbai_]
approval_policy = "never"
model = "mixedbread-ai/Mxbai-Rerank-Large-V2"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_moonshotai_kimi_k2_i]
approval_policy = "never"
model = "moonshotai/Kimi-K2-Instruct-0905"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.tog_openai_gpt_oss_120b]
approval_policy = "never"
model = "openai/gpt-oss-120b"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_openai_gpt_oss_20b]
approval_policy = "never"
model = "openai/gpt-oss-20b"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_openai_whisper_large]
approval_policy = "never"
model = "openai/whisper-large-v3"
model_provider = "togetherai"
model_reasoning_effort = "high"

[profiles.tog_scb10x_scb10x_typhoo]
approval_policy = "never"
model = "scb10x/scb10x-typhoon-2-1-gemma3-12b"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.tog_togethercomputer_moa]
approval_policy = "never"
model = "togethercomputer/MoA-1-Turbo"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_togethercomputer_ref]
approval_policy = "never"
model = "togethercomputer/Refuel-Llm-V2-Small"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.tog_togethercomputer_m2_]
approval_policy = "never"
model = "togethercomputer/m2-bert-80M-32k-retrieval"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.tog_zai_org_glm_4_5_air_]
approval_policy = "never"
model = "zai-org/GLM-4.5-Air-FP8"
model_provider = "togetherai"
model_reasoning_effort = "high"
model_context_window = 131072
