[model_providers.deepinfra]
base_url = "https://api.deepinfra.com/v1/openai"
name = "deepinfra"
wire_api = "chat"
env_key = "DEEPINFRA_API_KEY"

[profiles.dee_austism_chronos_herm]
approval_policy = "never"
model = "Austism/chronos-hermes-13b-v2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_baai_bge_base_en_v1_]
approval_policy = "never"
model = "BAAI/bge-base-en-v1.5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_baai_bge_en_icl]
approval_policy = "never"
model = "BAAI/bge-en-icl"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_baai_bge_large_en_v1]
approval_policy = "never"
model = "BAAI/bge-large-en-v1.5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_baai_bge_m3]
approval_policy = "never"
model = "BAAI/bge-m3"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_baai_bge_m3_multi]
approval_policy = "never"
model = "BAAI/bge-m3-multi"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_compvis_stable_diffu]
approval_policy = "never"
model = "CompVis/stable-diffusion-v1-4"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_gryphe_mythomax_l2_1]
approval_policy = "never"
model = "Gryphe/MythoMax-L2-13b-turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_koboldai_llama2_13b_]
approval_policy = "never"
model = "KoboldAI/LLaMA2-13B-Tiefighter"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_nousresearch_hermes_]
approval_policy = "never"
model = "NousResearch/Hermes-3-Llama-3.1-70B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_novasky_ai_sky_t1_32]
approval_policy = "never"
model = "NovaSky-AI/Sky-T1-32B-Preview"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_phind_phind_codellam]
approval_policy = "never"
model = "Phind/Phind-CodeLlama-34B-v2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qvq_72b_preview]
approval_policy = "never"
model = "Qwen/QVQ-72B-Preview"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwq_32b]
approval_policy = "never"
model = "Qwen/QwQ-32B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwq_32b_preview]
approval_policy = "never"
model = "Qwen/QwQ-32B-Preview"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen_image_edit]
approval_policy = "never"
model = "Qwen/Qwen-Image-Edit"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_72b_instr]
approval_policy = "never"
model = "Qwen/Qwen2-72B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_7b_instru]
approval_policy = "never"
model = "Qwen/Qwen2-7B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_5_72b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-72B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_5_7b_inst]
approval_policy = "never"
model = "Qwen/Qwen2.5-7B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_5_coder_3]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-32B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_5_coder_7]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-7B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen2_5_vl_32b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-32B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_14b]
approval_policy = "never"
model = "Qwen/Qwen3-14B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen/Qwen3-235B-A22B-Thinking-2507"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_30b_a3b]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_32b]
approval_policy = "never"
model = "Qwen/Qwen3-32B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_coder_480]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_qwen_qwen3_embedding]
approval_policy = "never"
model = "Qwen/Qwen3-Embedding-8B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_sao10k_l3_70b_euryal]
approval_policy = "never"
model = "Sao10K/L3-70B-Euryale-v2.1"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_sao10k_l3_8b_lunaris]
approval_policy = "never"
model = "Sao10K/L3-8B-Lunaris-v1-Turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_sao10k_l3_1_70b_eury]
approval_policy = "never"
model = "Sao10K/L3.1-70B-Euryale-v2.2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_sao10k_l3_3_70b_eury]
approval_policy = "never"
model = "Sao10K/L3.3-70B-Euryale-v2.3"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_xpuct_deliberate]
approval_policy = "never"
model = "XpucT/Deliberate"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_allenai_olmocr_7b_07]
approval_policy = "never"
model = "allenai/olmOCR-7B-0725-FP8"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_anthropic_claude_3_7]
approval_policy = "never"
model = "anthropic/claude-3-7-sonnet-latest"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_anthropic_claude_4_o]
approval_policy = "never"
model = "anthropic/claude-4-opus"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_anthropic_claude_4_s]
approval_policy = "never"
model = "anthropic/claude-4-sonnet"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_bigcode_starcoder2_1]
approval_policy = "never"
model = "bigcode/starcoder2-15b-instruct-v0.1"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_black_forest_labs_fl]
approval_policy = "never"
model = "black-forest-labs/FLUX.1-Kontext-dev"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_cognitivecomputation]
approval_policy = "never"
model = "cognitivecomputations/dolphin-2.9.1-llama-3-70b"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_deepinfra_airoboros_]
approval_policy = "never"
model = "deepinfra/airoboros-70b"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai/DeepSeek-V3.1"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_deepseek_ai_janus_pr]
approval_policy = "never"
model = "deepseek-ai/Janus-Pro-7B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_codegemma_7b_]
approval_policy = "never"
model = "google/codegemma-7b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemini_1_5_fl]
approval_policy = "never"
model = "google/gemini-1.5-flash-8b"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemini_2_0_fl]
approval_policy = "never"
model = "google/gemini-2.0-flash-001"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemini_2_5_fl]
approval_policy = "never"
model = "google/gemini-2.5-flash"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemini_2_5_pr]
approval_policy = "never"
model = "google/gemini-2.5-pro"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_1_1_7b_]
approval_policy = "never"
model = "google/gemma-1.1-7b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_2_27b_i]
approval_policy = "never"
model = "google/gemma-2-27b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_2_9b_it]
approval_policy = "never"
model = "google/gemma-2-9b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_3_12b_i]
approval_policy = "never"
model = "google/gemma-3-12b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_3_27b_i]
approval_policy = "never"
model = "google/gemma-3-27b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_google_gemma_3_4b_it]
approval_policy = "never"
model = "google/gemma-3-4b-it"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_intfloat_e5_base_v2]
approval_policy = "never"
model = "intfloat/e5-base-v2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_intfloat_e5_large_v2]
approval_policy = "never"
model = "intfloat/e5-large-v2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_intfloat_multilingua]
approval_policy = "never"
model = "intfloat/multilingual-e5-large-instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_lizpreciatior_lzlv_7]
approval_policy = "never"
model = "lizpreciatior/lzlv_70b_fp16_hf"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mattshumer_reflectio]
approval_policy = "never"
model = "mattshumer/Reflection-Llama-3.1-70B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_2_1]
approval_policy = "never"
model = "meta-llama/Llama-2-13b-chat-hf"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_2_7]
approval_policy = "never"
model = "meta-llama/Llama-2-70b-chat-hf"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_3_2]
approval_policy = "never"
model = "meta-llama/Llama-3.2-90B-Vision-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_3_3]
approval_policy = "never"
model = "meta-llama/Llama-3.3-70B-Instruct-Turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_4_m]
approval_policy = "never"
model = "meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_4_s]
approval_policy = "never"
model = "meta-llama/Llama-4-Scout-17B-16E-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_llama_gua]
approval_policy = "never"
model = "meta-llama/Llama-Guard-4-12B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_meta_llama_meta_llam]
approval_policy = "never"
model = "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_microsoft_phi_3_medi]
approval_policy = "never"
model = "microsoft/Phi-3-medium-4k-instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_microsoft_phi_4_mult]
approval_policy = "never"
model = "microsoft/Phi-4-multimodal-instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_microsoft_wizardlm_2]
approval_policy = "never"
model = "microsoft/WizardLM-2-8x22B"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_microsoft_phi_4]
approval_policy = "never"
model = "microsoft/phi-4"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_microsoft_phi_4_reas]
approval_policy = "never"
model = "microsoft/phi-4-reasoning-plus"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mistralai_devstral_s]
approval_policy = "never"
model = "mistralai/Devstral-Small-2507"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mistralai_mistral_7b]
approval_policy = "never"
model = "mistralai/Mistral-7B-Instruct-v0.3"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mistralai_mistral_ne]
approval_policy = "never"
model = "mistralai/Mistral-Nemo-Instruct-2407"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mistralai_mistral_sm]
approval_policy = "never"
model = "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_mistralai_mixtral_8x]
approval_policy = "never"
model = "mistralai/Mixtral-8x7B-Instruct-v0.1"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_moonshotai_kimi_k2_i]
approval_policy = "never"
model = "moonshotai/Kimi-K2-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_nvidia_llama_3_1_nem]
approval_policy = "never"
model = "nvidia/Llama-3.1-Nemotron-70B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_nvidia_nemotron_4_34]
approval_policy = "never"
model = "nvidia/Nemotron-4-340B-Instruct"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_openai_gpt_oss_120b]
approval_policy = "never"
model = "openai/gpt-oss-120b"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_openai_gpt_oss_20b]
approval_policy = "never"
model = "openai/gpt-oss-20b"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_openbmb_minicpm_llam]
approval_policy = "never"
model = "openbmb/MiniCPM-Llama3-V-2_5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_openchat_openchat_3_]
approval_policy = "never"
model = "openchat/openchat_3.5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_run_diffusion_jugger]
approval_policy = "never"
model = "run-diffusion/Juggernaut-Lightning-Flux"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_runwayml_stable_diff]
approval_policy = "never"
model = "runwayml/stable-diffusion-v1-5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_sentence_transformer]
approval_policy = "never"
model = "sentence-transformers/paraphrase-MiniLM-L6-v2"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_shibing624_text2vec_]
approval_policy = "never"
model = "shibing624/text2vec-base-chinese"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_stabilityai_sd3_5]
approval_policy = "never"
model = "stabilityai/sd3.5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_stabilityai_sd3_5_me]
approval_policy = "never"
model = "stabilityai/sd3.5-medium"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_stabilityai_sdxl_tur]
approval_policy = "never"
model = "stabilityai/sdxl-turbo"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_stabilityai_stable_d]
approval_policy = "never"
model = "stabilityai/stable-diffusion-2-1"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_thenlper_gte_base]
approval_policy = "never"
model = "thenlper/gte-base"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_thenlper_gte_large]
approval_policy = "never"
model = "thenlper/gte-large"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_zai_org_glm_4_5]
approval_policy = "never"
model = "zai-org/GLM-4.5"
model_provider = "deepinfra"
model_reasoning_effort = "high"

[profiles.dee_zai_org_glm_4_5_air]
approval_policy = "never"
model = "zai-org/GLM-4.5-Air"
model_provider = "deepinfra"
model_reasoning_effort = "high"
