[model_providers.infermatic]
base_url = "https://api.totalgpt.ai/v1"
name = "infermatic"
wire_api = "chat"
env_key = "INFERMATIC_API_KEY"

[profiles.inf_doctor_shotgun_l3_3_]
approval_policy = "never"
model = "Doctor-Shotgun-L3.3-70B-Magnum-v4-SE"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_l3_1_70b_euryale_v2_]
approval_policy = "never"
model = "L3.1-70B-Euryale-v2.2-FP8-Dynamic"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_llama_3_2_11b_vision]
approval_policy = "never"
model = "Llama-3.2-11B-Vision-Instruct-Turbo"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_meta_llama_guard_2_8]
approval_policy = "never"
model = "Meta-Llama-Guard-2-8B"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_midnight_miqu_70b_v1]
approval_policy = "never"
model = "Midnight-Miqu-70B-v1.5"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_mixtral_8x7b_instruc]
approval_policy = "never"
model = "Mixtral-8x7B-Instruct-v0.1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_nousresearch_deepher]
approval_policy = "never"
model = "NousResearch-DeepHermes-3-Mistral-24B-Preview"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen-Qwen3-235B-A22B-Thinking-2507"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_qwen_qwen3_30b_a3b]
approval_policy = "never"
model = "Qwen-Qwen3-30B-A3B"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_qwen2_72b_instruct]
approval_policy = "never"
model = "Qwen2-72B-Instruct"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_sao10k_70b_l3_3_cirr]
approval_policy = "never"
model = "Sao10K-70B-L3.3-Cirrus-x1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_sao10k_72b_qwen2_5_k]
approval_policy = "never"
model = "Sao10K-72B-Qwen2.5-Kunou-v1-FP8-Dynamic"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_sao10k_l3_1_70b_hana]
approval_policy = "never"
model = "Sao10K-L3.1-70B-Hanami-x1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_sao10k_l3_3_70b_eury]
approval_policy = "never"
model = "Sao10K-L3.3-70B-Euryale-v2.3-FP8-Dynamic"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_tts_hexgrad_kokoro_8]
approval_policy = "never"
model = "TTS-hexgrad-Kokoro-82M"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_thedrummer_anubis_70]
approval_policy = "never"
model = "TheDrummer-Anubis-70B-v1-FP8-Dynamic"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_thedrummer_fallen_ll]
approval_policy = "never"
model = "TheDrummer-Fallen-Llama-3.3-R1-70B-v1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_thedrummer_rocinante]
approval_policy = "never"
model = "TheDrummer-Rocinante-12B-v1.1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_thedrummer_unslopnem]
approval_policy = "never"
model = "TheDrummer-UnslopNemo-12B-v4.1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_thedrummer_valkyrie_]
approval_policy = "never"
model = "TheDrummer-Valkyrie-49B-v1"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_anthracite_org_magnu]
approval_policy = "never"
model = "anthracite-org-magnum-v4-72b-FP8-Dynamic"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai-DeepSeek-R1-Distill-Llama-70B"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_intfloat_multilingua]
approval_policy = "never"
model = "intfloat-multilingual-e5-base"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_nvidia_llama_3_1_nem]
approval_policy = "never"
model = "nvidia-Llama-3.1-Nemotron-70B-Instruct-HF"
model_provider = "infermatic"
model_reasoning_effort = "high"

[profiles.inf_raifle_sorcererlm_8x]
approval_policy = "never"
model = "rAIfle-SorcererLM-8x22b-bf16"
model_provider = "infermatic"
model_reasoning_effort = "high"
