[model_providers.chutes]
base_url = "https://llm.chutes.ai/v1"
name = "chutes"
wire_api = "chat"
env_key = "CHUTES_API_KEY"

[profiles.chu_arliai_qwq_32b_arlia]
approval_policy = "never"
model = "ArliAI/QwQ-32B-ArliAI-RpR-v1"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_bytedance_seed_seed_]
approval_policy = "never"
model = "ByteDance-Seed/Seed-OSS-36B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_nousresearch_deepher]
approval_policy = "never"
model = "NousResearch/DeepHermes-3-Mistral-24B-Preview"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_nousresearch_hermes_]
approval_policy = "never"
model = "NousResearch/Hermes-4-70B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_qwen_qwen2_5_72b_ins]
approval_policy = "never"
model = "Qwen/Qwen2.5-72B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_qwen_qwen2_5_coder_3]
approval_policy = "never"
model = "Qwen/Qwen2.5-Coder-32B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_qwen_qwen2_5_vl_32b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-32B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 16384

[profiles.chu_qwen_qwen2_5_vl_72b_]
approval_policy = "never"
model = "Qwen/Qwen2.5-VL-72B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_qwen_qwen3_14b]
approval_policy = "never"
model = "Qwen/Qwen3-14B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.chu_qwen_qwen3_235b_a22b]
approval_policy = "never"
model = "Qwen/Qwen3-235B-A22B-Thinking-2507"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_qwen_qwen3_30b_a3b]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.chu_qwen_qwen3_30b_a3b_i]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_qwen_qwen3_30b_a3b_t]
approval_policy = "never"
model = "Qwen/Qwen3-30B-A3B-Thinking-2507"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_qwen_qwen3_32b]
approval_policy = "never"
model = "Qwen/Qwen3-32B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.chu_qwen_qwen3_8b]
approval_policy = "never"
model = "Qwen/Qwen3-8B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.chu_qwen_qwen3_coder_30b]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-30B-A3B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_qwen_qwen3_coder_480]
approval_policy = "never"
model = "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_tesslate_uigen_x_32b]
approval_policy = "never"
model = "Tesslate/UIGEN-X-32B-0727"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 40960

[profiles.chu_thedrummer_gemmasutr]
approval_policy = "never"
model = "TheDrummer/Gemmasutra-Pro-27B-v1.1"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.chu_thedrummer_skyfall_3]
approval_policy = "never"
model = "TheDrummer/Skyfall-36B-v2"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_thedrummer_tunguska_]
approval_policy = "never"
model = "TheDrummer/Tunguska-39B-v1"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_agentica_org_deepcod]
approval_policy = "never"
model = "agentica-org/DeepCoder-14B-Preview"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 96000

[profiles.chu_all_hands_openhands_]
approval_policy = "never"
model = "all-hands/openhands-lm-32b-v0.1-ep3"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 16384

[profiles.chu_chutesai_devstral_sm]
approval_policy = "never"
model = "chutesai/Devstral-Small-2505"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_chutesai_mistral_sma]
approval_policy = "never"
model = "chutesai/Mistral-Small-3.2-24B-Instruct-2506"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_cognitivecomputation]
approval_policy = "never"
model = "cognitivecomputations/Dolphin3.0-R1-Mistral-24B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_deepseek_ai_deepseek]
approval_policy = "never"
model = "deepseek-ai/DeepSeek-V3.1-Base"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 163840

[profiles.chu_meituan_longcat_long]
approval_policy = "never"
model = "meituan-longcat/LongCat-Flash-Chat-FP8"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_microsoft_mai_ds_r1_]
approval_policy = "never"
model = "microsoft/MAI-DS-R1-FP8"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 163840

[profiles.chu_moonshotai_kimi_dev_]
approval_policy = "never"
model = "moonshotai/Kimi-Dev-72B"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_moonshotai_kimi_k2_i]
approval_policy = "never"
model = "moonshotai/Kimi-K2-Instruct-0905"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 262144

[profiles.chu_moonshotai_kimi_vl_a]
approval_policy = "never"
model = "moonshotai/Kimi-VL-A3B-Thinking"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_nvidia_llama_3_3_nem]
approval_policy = "never"
model = "nvidia/Llama-3_3-Nemotron-Super-49B-v1_5"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_openai_gpt_oss_120b]
approval_policy = "never"
model = "openai/gpt-oss-120b"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_openai_gpt_oss_20b]
approval_policy = "never"
model = "openai/gpt-oss-20b"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_shisa_ai_shisa_v2_ll]
approval_policy = "never"
model = "shisa-ai/shisa-v2-llama3.3-70b"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_tencent_hunyuan_a13b]
approval_policy = "never"
model = "tencent/Hunyuan-A13B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_tngtech_deepseek_r1t]
approval_policy = "never"
model = "tngtech/DeepSeek-R1T-Chimera"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 163840

[profiles.chu_tngtech_deepseek_tng]
approval_policy = "never"
model = "tngtech/DeepSeek-TNG-R1T2-Chimera"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 163840

[profiles.chu_unsloth_llama_3_2_1b]
approval_policy = "never"
model = "unsloth/Llama-3.2-1B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 16384

[profiles.chu_unsloth_llama_3_2_3b]
approval_policy = "never"
model = "unsloth/Llama-3.2-3B-Instruct"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 16384

[profiles.chu_unsloth_mistral_nemo]
approval_policy = "never"
model = "unsloth/Mistral-Nemo-Instruct-2407"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_unsloth_mistral_smal]
approval_policy = "never"
model = "unsloth/Mistral-Small-24B-Instruct-2501"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_unsloth_gemma_2_9b_i]
approval_policy = "never"
model = "unsloth/gemma-2-9b-it"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 8192

[profiles.chu_unsloth_gemma_3_12b_]
approval_policy = "never"
model = "unsloth/gemma-3-12b-it"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 96000

[profiles.chu_unsloth_gemma_3_27b_]
approval_policy = "never"
model = "unsloth/gemma-3-27b-it"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 96000

[profiles.chu_unsloth_gemma_3_4b_i]
approval_policy = "never"
model = "unsloth/gemma-3-4b-it"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 96000

[profiles.chu_zai_org_glm_4_32b_04]
approval_policy = "never"
model = "zai-org/GLM-4-32B-0414"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768

[profiles.chu_zai_org_glm_4_5_air]
approval_policy = "never"
model = "zai-org/GLM-4.5-Air"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_zai_org_glm_4_5_fp8]
approval_policy = "never"
model = "zai-org/GLM-4.5-FP8"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 131072

[profiles.chu_zai_org_glm_4_5v_fp8]
approval_policy = "never"
model = "zai-org/GLM-4.5V-FP8"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 65536

[profiles.chu_zai_org_glm_z1_32b_0]
approval_policy = "never"
model = "zai-org/GLM-Z1-32B-0414"
model_provider = "chutes"
model_reasoning_effort = "high"
model_context_window = 32768
